### Numpy 

In [1]:
import numpy as np

### Datatypes and attributes

In [ ]:
# vector
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [ ]:
# matrix

a2 = np.array([[1, 2.1, 3.3],
[4, 5.2, 6.5]])

In [6]:
a2 

array([[1. , 2.1, 3.3],
       [4. , 5.2, 6.5]])

In [ ]:
# ndimensional

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(2, 3)

In [14]:
a3.shape

(2, 3, 3)

In [15]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [16]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [17]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [18]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [19]:
import pandas as pd

In [20]:
df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.1,3.3
1,4.0,5.2,6.5


### Creating arrays

In [ ]:
sample_array = np.array([1, 2, 3])

In [21]:
ones = np.ones((2,3))

In [22]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
ones.dtype

dtype('float64')

In [24]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros((2,3))

In [26]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
range_array = np.arange(0, 10, 2)

In [29]:
range_array = np.arange(0, 10, 2)

In [30]:
random_array = np.random.randint(0, 10, size=(3,5))

In [31]:
random_array

array([[8, 7, 7, 8, 7],
       [1, 6, 1, 7, 3],
       [1, 0, 0, 7, 1]])

In [32]:
random_array.size

15

In [33]:
random_array.shape

(3, 5)

In [35]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.39337666, 0.92205582, 0.31443675],
       [0.87227318, 0.26906703, 0.43204286],
       [0.1816992 , 0.69141575, 0.34628175],
       [0.70773464, 0.66101707, 0.57649704],
       [0.87399456, 0.45502722, 0.67573058]])

In [36]:
random_array_2.shape

(5, 3)

In [37]:
random_array_2.size

15

In [38]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.84574564, 0.65507791, 0.02758599],
       [0.42059446, 0.05780444, 0.50516763],
       [0.58038944, 0.36292156, 0.02005481],
       [0.44009564, 0.49481123, 0.07491694],
       [0.16104969, 0.81769632, 0.08851321]])

In [ ]:
# pseudo random numbers
np.random.seed()